version: 0.0
os: linux
files:
  - source: bin/incus
    destination: /usr/sbin
  - source: scripts/initd.sh
    destination: /etc/init.d
permissions:
  - object: /usr/sbin/incus
    owner: root
    group: root
    mode: 755
  - object: /etc/init.d/incus
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/codedeploy/stop_monit.sh
      timeout: 60
      runas: root
    - location: scripts/codedeploy/deregister_from_elb_and_stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/start.sh
      timeout: 60
      runas: root
    - location: scripts/codedeploy/register_with_elb.sh
      timeout: 600
      runas: root
    - location: scripts/codedeploy/start_monit.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/codedeploy/check.sh
      timeout: 60
      runas: root

